// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa-iMev2cRN5LlQnHyIoC8bWlluYuVHKQ',
    appId: '1:1046465987175:web:82b33397ba6586cbc60ac2',
    messagingSenderId: '1046465987175',
    projectId: 'smart-weather-app-7061f',
    authDomain: 'smart-weather-app-7061f.firebaseapp.com',
    storageBucket: 'smart-weather-app-7061f.firebasestorage.app',
    measurementId: 'G-R8M7H76PYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc_PgsOd_r2hNfHOblF_xe2lHfPNSV4ZY',
    appId: '1:1046465987175:android:052fc5c421488df5c60ac2',
    messagingSenderId: '1046465987175',
    projectId: 'smart-weather-app-7061f',
    storageBucket: 'smart-weather-app-7061f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKf7LL_DP8iD-tG4luzimEjG_TeufKhyY',
    appId: '1:1046465987175:ios:f7b54206d99565dfc60ac2',
    messagingSenderId: '1046465987175',
    projectId: 'smart-weather-app-7061f',
    storageBucket: 'smart-weather-app-7061f.firebasestorage.app',
    iosBundleId: 'com.example.weatherAppSarmad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKf7LL_DP8iD-tG4luzimEjG_TeufKhyY',
    appId: '1:1046465987175:ios:f7b54206d99565dfc60ac2',
    messagingSenderId: '1046465987175',
    projectId: 'smart-weather-app-7061f',
    storageBucket: 'smart-weather-app-7061f.firebasestorage.app',
    iosBundleId: 'com.example.weatherAppSarmad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa-iMev2cRN5LlQnHyIoC8bWlluYuVHKQ',
    appId: '1:1046465987175:web:6a0bedbe30830004c60ac2',
    messagingSenderId: '1046465987175',
    projectId: 'smart-weather-app-7061f',
    authDomain: 'smart-weather-app-7061f.firebaseapp.com',
    storageBucket: 'smart-weather-app-7061f.firebasestorage.app',
    measurementId: 'G-5906DQXBGE',
  );
}
